version: '3.8'

services:
  django:
    build: .
    container_name: django
    command: >
      sh -c "sleep 5 && python freelance/manage.py migrate && python freelance/manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/usr/src/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - pgdb

  pgdb:
    image: postgres
    environment:
      - POSTGRES_DB=INNOfreelance
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=consul
    container_name: pgdb
    volumes:
      - pgdb_data:/var/lib/postgresql/data/


volumes:
  pgdb_data: